galaxy_info:
  role_name: cagw_certificate_request
  author: Sapna Jain
  description: Entrust Certificate Gateway (CAGW) API Integration - Request/Get/Hold/Unhold/Revoke an SSL certificate from the CAGW API.
  company: Entrust

  license: MIT

  min_ansible_version: 2.9
 
  platforms:
    - name: Alpine
      versions:
        - all
    - name: Amazon
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: SLES
      versions:
        - all
        
  galaxy_tags:
    - web
    - server
    - development
    - ssl
    - tls
    - api
    - entrust
    - certificates
    - management

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
  
