---
# vars file for galaxy-edc-roles

working_path: ~/entrust-ansible-collection/roles/common
# Values used for private key generation
privatekey_path: '{{ working_path }}/files/prvkey.pem'
privatekey_passphrase: Passphrase2525!

# Values used for the CSR generation
csr_path: '{{ working_path }}/files/csr.pem'
common_name: cn
organization_name: org_name
locality_name: Kanata
country_name: CA
state_or_province_name: ontario

entrust_host: 1.1.1.1
entrust_port: 8081
remaining_days: 30
force: true
entrust_text1: Admin
entrust_text2: Invoice 25
entrust_number1: 342
entrust_date1: 2018-01-01
entrust_email1: sales@ansible.testcertificates.com
validate_certs: False

# PEM encoded certificate and key information
# Remember to replace the contents of these files with your actual client keypair,
# or change this path to point to another location where they can be found.
entrust_cagw_api_cert: '{{ working_path }}/files/cert.pem'
entrust_cagw_api_cert_key: '{{ working_path }}/files/key.pem'
cagw_api_specification_path: '{{ working_path }}/files/cagw-api.yaml'
dn: /C=CA/O=/CN=example.com

# example 1
example1_cert_path: '{{ working_path }}/files/issuedcert_1.pem'
example1_request_type: new
example1_enrollment_format: X509
example1_ca_id: ca_id
example1_profile_id: profile_id

#example 2
example2_cert_path: '{{ working_path }}/files/issuedcert_2.pem'
#Below can be the parameters for subjectAltName
example2_dNSName: example.com
example2_iPAddress: 1.1.1.1
example2_directoryName: cn=john doe,o=example inc,c=us
example2_uniformResourceIdentifier: http://example.com/

#example 3
example3_cert_path: '{{ working_path }}/files/issuedcert_3.pem'
example3_request_type: get
example3_serialNumber: 318faaed6e

# example 4
example4_cert_path: '{{ working_path }}/files/issuedcert_4.pem'
example4_request_type: new
example4_enrollment_format: PKCS12
example4_ca_id: ca_id
example4_profile_id: p12_profile_id
example4_p12_password: Password@2018
example4_dn: CN=example.com,O=ent,C=CA

# When Connection type is ECS then below arguments are passed to ECS CA
# example 5
example5_cert_path: '{{ working_path }}/files/issuedcert_5.pem'
example5_request_type: new
example5_enrollment_format: X509
example5_ca_id: ca-id
example5_profile_id: profile_id
entrust_requester_name: John Clark
entrust_requester_email: john.clark@example.com
entrust_requester_phone: 1-613-555-5555  # e.g. 16135555555
entrust_tracking_info: 3-232-32

#TEST 6
example6_request_type: action
example6_action_type: HoldAction
example6_action_reason: unspecified
example6_serialNumber: 318f84a2b87a59d6e
